### ISSUE TITLE
Zugang

### ISSUE THREAD

**Issue by makoeppel** [joshuakuepper/Challenge-1757#3]
Hallo zusammen,

bin von der Gruppe #1757_modellierung_ml und würde gerne Zugang für das Git haben um einen Branch für die ML Modelle zu erstellen.

LG,
Marius

**Comment by moritzhoferer** [comment]
Hast du dich im Spreadsheet eingetragen, dann fuegt dich @joshuakuepper hinzu.

**Comment by makoeppel** [comment]
Bin in dem Sheet drin

**Comment by moritzhoferer** [comment]
Da ich gesehen habe, dass du erfolgreich einen Commit gemacht hast, schliesse ich das Issue.
